### PR TITLE
Fix/allow capital 'z' in search value

### LINKED ISSUE #7: Z and _ is matched as suspicious characters
When either a Z or a underscore (_) appears on the right hand side of a :: it is matched as suspicious content, and the string is filtered away. 

I believe what is intended to be matched as suspicious content is \Z, \_ (and \%) but since we already match backslash \, these are superfluous and seems to be causing issues.

### PR DESCRIPTION
**Pull request by kno-trackunit**
Fixes #7

### CODE REVIEW

**Review by gringostar — APPROVED** [review]

**Comment by langecode** [comment]
I have seen it - will take a look asap ;)

File: src/main/java/io/openapitools/api/capabilities/Sanitizer.java [hunk 1]
```diff
@@ -6,7 +6,7 @@
  * API input sanitizer in a rudimental version.
  */
 public final class Sanitizer {
-    private static final String[] SUSPICIOUS_CONTENT = {"\'", "\"", "\\", "%", "\\%", "\\_", "\0", "\b", "\n", "\t", "\r", "\\Z", "?", "#"};
```
Comment (langecode) [inline src/main/java/io/openapitools/api/capabilities/Sanitizer.java:9]: I see the point in `\%` already being captured as both `\` and `%` are already caught. Seems this is actually just an `char[]` now instead of `String[]` :-)

**Review by langecode — APPROVED** [review]
Looks ok - possibly the "suspecious" array should be converted into `char[]` instead of `String[]`

File: src/main/java/io/openapitools/api/capabilities/Sanitizer.java (hunk 1 above)
Comment (kno-trackunit) [reply src/main/java/io/openapitools/api/capabilities/Sanitizer.java:9]: I will make the update to char[] :)
